### PR TITLE
stick to just two Dockerfiles: one for base, one on top

### PR DESCRIPTION
**Pull request by boegel**
process:

```bash
# build base container
docker build -f Dockerfile.base-centos7 -t easybuilders/base:centos7-eb4.2.1 .
# build software container with SciPy-bundle and all deps, for Haswell
docker build -f Dockerfile.easybuild-centos7 --build-arg CPU_ARCH=haswell -t easybuilders/test:centos7-SciPy-bundle-foss-2020a .
```

or:

```bash
# build base container
docker build -f Dockerfile.base-centos7 -t easybuilders/base:centos7-eb4.2.1 .
# build container for GCC-9.3.0 on Haswell
docker build -f Dockerfile.easybuild-centos7 --build-arg EASYCONFIG=GCC-9.3.0.eb -t easybuilders/test:centos7-GCC-9.3.0 .
# build container for foss-2020a on Haswell, on top of GCC-9.3.0 container
docker build -f Dockerfile.easybuild-centos7 --build-arg IMG_NAME=test --build-arg IMG_TAG=centos7-GCC-9.3.0 --build-arg EASYCONFIG=foss-2020a.eb -t easybuilders/test:centos7-foss-2020a .
# build software container with SciPy-bundle for Haswell, on top of foss-2020a container
docker build -f Dockerfile.easybuild-centos7 --build-arg IMG_NAME=test --build-arg IMG_TAG=centos7-foss-2020a -t easybuilders/test:centos7-SciPy-bundle-foss-2020a .

### CODE REVIEW

**Comment by kniec** [comment]
As discussed briefly - that moves the logic into the build-script and does not keep it within a succession of Dockerfiles. Depends on how the build-chain is build I suggest. :)

**Comment by boegel** [comment]
@ChristianKniep The last commits should deal with getting rid of the system-wide `eb` installation and using the `EasyBuild` module instead for the installations, while making sure the `EasyBuild` module is no longer loaded automatically in the final tutorial image...

**Comment by kniec** [comment]
Please add this file `entrypoint.sh`:
```
#!/bin/bash

 ml use /easybuild/modules/all
 ml EasyBuild
 bash
```
and add this to the Dockerfile.base - I reckon after pip uninstall:
```
# Add entrypoint
COPY entrypoint.sh /usr/local/bin/entrypoint.sh 
CMD ["/usr/local/bin/entrypoint.sh"]
```

**Comment by boegel** [comment]
> Please add this file `entrypoint.sh`:

As discussed, using `.bashrc` login script instead (which is easier to undo)

**Comment by boegel** [comment]
Merging this, seems to be working as intended...

**Pull request merged**
